'use client'

import React, { useState } from 'react'
import Link from 'next/link'
import { toast } from 'sonner'
import { StitchShell } from '@/components/layout/stitch-shell'
import { FarmTerrainTwin } from '@/components/three/farm-terrain-twin'
import { useFarmContext } from '@/hooks/use-farm-context'
import { recommendCrops } from '@/lib/api'
import type { CropRecommendation } from '@/lib/api'

export default function CropIntelligencePage() {
  const { context, user, farmProfile } = useFarmContext()
  const [recommendations, setRecommendations] = useState<CropRecommendation[]>([])
  const [loading, setLoading] = useState(false)
  const [hasAnalyzed, setHasAnalyzed] = useState(false)

  const farmLocation = farmProfile?.location || context.location || 'Anekal, Bengaluru Urban, Karnataka'
  const soilType = farmProfile?.soil_type || context.soilType || 'Red sandy loam'
  const landSize = farmProfile?.land_size_acres || context.landSizeAcres || 3.5
  const water = farmProfile?.water_availability || context.waterAvailability || 'moderate'
  const season = farmProfile?.season || context.season || 'Kharif'
  const currentCrop = farmProfile?.current_crop || context.primaryCrop || 'Tomato'

  const handleAnalyzeFarm = async () => {
    setLoading(true)
    try {
      const res = await recommendCrops({
        location: farmLocation,
        soil: soilType,
        waterAvailability: (water.toLowerCase() === 'high' ? 'high' : water.toLowerCase() === 'low' ? 'low' : 'moderate') as 'low' | 'moderate' | 'high',
        landSize: Number(landSize),
        season: season,
        farmerGoal: (farmProfile?.farming_goal || context.goal || 'profit') as any,
      })
      setRecommendations(res.recommendations || [])
      setHasAnalyzed(true)
      toast.success('Crop recommendations generated by Gemini AI!')
    } catch (err: any) {
      toast.error(err?.message || 'Could not complete farm analysis. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <StitchShell>
      <div className="w-full max-w-[1680px] mx-auto px-4 sm:px-6 lg:px-12 py-6 flex flex-col gap-8">
        {/* Top Header & Context Badges */}
        <div className="flex flex-wrap items-center justify-between gap-4 pb-2 border-b border-outline-variant/30">
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 bg-surface-container-high/80 border border-primary/25 px-3 py-1 rounded-full shadow-sm">
              <span className="w-2 h-2 rounded-full bg-primary" />
              <span className="font-label-code-sm text-xs text-primary uppercase font-bold">
                Crop Intelligence
              </span>
            </div>
            <div className="flex items-center gap-2 bg-surface-container/60 border border-outline-variant/30 px-3 py-1 rounded-full text-on-surface-variant font-label-code-sm text-xs">
              <span className="material-symbols-outlined text-sm text-secondary">pin_drop</span>
              <span>{farmLocation}</span>
            </div>
          </div>

          <Link
            href="/copilot"
            className="px-4 py-1.5 rounded-full bg-primary-container text-on-primary-container font-label-code-sm text-xs uppercase font-bold shadow-md hover:scale-105 transition-all flex items-center gap-2"
          >
            <span className="material-symbols-outlined text-sm">psychology</span>
            <span>Ask AI Copilot</span>
          </Link>
        </div>

        {/* Hero Section: 3D Twin & Farm Context Summary */}
        <div className="grid grid-cols-1 xl:grid-cols-12 gap-8 items-start">
          {/* Left: 3D Canvas */}
          <div className="xl:col-span-7 flex flex-col gap-4">
            <div className="flex flex-col gap-1">
              <h1 className="font-headline-lg text-2xl sm:text-3xl font-bold text-white tracking-tight">
                Crop Suitability Advisor
              </h1>
              <p className="font-body-md text-sm text-on-surface-variant max-w-xl">
                Bhoomi Mithra analyzes your regional soil profile, seasonal rainfall, and acreage to recommend viable alternatives.
              </p>
            </div>

            <div className="relative w-full rounded-3xl overflow-hidden bg-surface-container-low border border-primary/25 shadow-2xl p-3">
              <div className="w-full h-[360px] sm:h-[420px] rounded-2xl relative overflow-hidden bg-surface-container-lowest">
                <FarmTerrainTwin height={420} cropName={currentCrop} />
                <div className="absolute top-4 left-4 z-20 px-3 py-1.5 rounded-xl bg-surface-container-lowest/80 border border-primary/20 backdrop-blur-md flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-primary" />
                  <span className="font-label-code-sm text-[10px] text-white uppercase font-bold">
                    Target: {currentCrop}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Right: Saved Conditions Card + CTA */}
          <div className="xl:col-span-5 flex flex-col gap-4">
            <div className="bg-surface-container-low/70 backdrop-blur-2xl border border-outline-variant/30 rounded-3xl p-6 shadow-xl space-y-6">
              <div className="flex items-center justify-between border-b border-outline-variant/20 pb-3">
                <h2 className="font-headline-sm text-lg font-bold text-white flex items-center gap-2">
                  <span className="material-symbols-outlined text-primary text-xl">tune</span>
                  Active Farm Profile
                </h2>
                <span className="px-2.5 py-0.5 rounded-full bg-primary/20 border border-primary/40 text-primary text-[10px] font-label-code-sm uppercase font-bold">
                  {user ? 'D1 Synchronized' : 'Profile Node'}
                </span>
              </div>

              <div className="grid grid-cols-2 gap-3 text-xs">
                <div className="p-3 rounded-2xl bg-surface-container-high/60 border border-outline-variant/30">
                  <span className="block text-[10px] uppercase font-label-code-sm text-on-surface-variant mb-1">
                    Location
                  </span>
                  <span className="font-bold text-on-surface truncate block">{farmLocation}</span>
                </div>

                <div className="p-3 rounded-2xl bg-surface-container-high/60 border border-outline-variant/30">
                  <span className="block text-[10px] uppercase font-label-code-sm text-on-surface-variant mb-1">
                    Soil Profile
                  </span>
                  <span className="font-bold text-on-surface truncate block">{soilType}</span>
                </div>

                <div className="p-3 rounded-2xl bg-surface-container-high/60 border border-outline-variant/30">
                  <span className="block text-[10px] uppercase font-label-code-sm text-on-surface-variant mb-1">
                    Land Size
                  </span>
                  <span className="font-bold text-primary truncate block">{landSize} Acres</span>
                </div>

                <div className="p-3 rounded-2xl bg-surface-container-high/60 border border-outline-variant/30">
                  <span className="block text-[10px] uppercase font-label-code-sm text-on-surface-variant mb-1">
                    Water Access
                  </span>
                  <span className="font-bold text-secondary truncate block capitalize">{water}</span>
                </div>

                <div className="p-3 rounded-2xl bg-surface-container-high/60 border border-outline-variant/30">
                  <span className="block text-[10px] uppercase font-label-code-sm text-on-surface-variant mb-1">
                    Season
                  </span>
                  <span className="font-bold text-on-surface truncate block">{season}</span>
                </div>

                <div className="p-3 rounded-2xl bg-surface-container-high/60 border border-outline-variant/30">
                  <span className="block text-[10px] uppercase font-label-code-sm text-on-surface-variant mb-1">
                    Current Crop
                  </span>
                  <span className="font-bold text-secondary truncate block">{currentCrop}</span>
                </div>
              </div>

              {/* Action Button: 1 Click = 1 Request */}
              <button
                type="button"
                onClick={handleAnalyzeFarm}
                disabled={loading}
                className="w-full py-4 rounded-2xl bg-gradient-to-r from-primary to-primary-container text-surface font-bold text-sm tracking-wider uppercase shadow-[0_0_20px_rgba(112,96,249,0.4)] hover:shadow-[0_0_30px_rgba(112,96,249,0.6)] transition-all flex items-center justify-center gap-2"
              >
                {loading ? (
                  <>
                    <span className="material-symbols-outlined animate-spin text-lg">progress_activity</span>
                    <span>Analyzing Farm with Gemini...</span>
                  </>
                ) : (
                  <>
                    <span className="material-symbols-outlined text-lg">psychology</span>
                    <span>Analyze My Farm</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Results Section */}
        <div className="space-y-6 pt-4">
          <div className="flex items-center justify-between border-b border-outline-variant/20 pb-3">
            <div>
              <h2 className="font-headline-sm text-xl text-white font-bold flex items-center gap-2">
                <span className="material-symbols-outlined text-secondary text-2xl">grain</span>
                Recommended Crops
              </h2>
              <p className="text-xs text-on-surface-variant">
                Derived from soil moisture capacity, regional mandi demand, and season window.
              </p>
            </div>
            {hasAnalyzed && (
              <span className="px-3 py-1 rounded-full bg-secondary/10 border border-secondary/30 text-secondary text-xs font-label-code-sm uppercase font-semibold">
                AI Generated
              </span>
            )}
          </div>

          {!hasAnalyzed ? (
            <div className="p-12 rounded-3xl bg-surface-container-low/50 border border-outline-variant/20 text-center space-y-4">
              <div className="w-16 h-16 rounded-2xl bg-surface-container-high mx-auto flex items-center justify-center text-primary">
                <span className="material-symbols-outlined text-3xl">psychiatry</span>
              </div>
              <h3 className="font-headline-sm text-lg text-white font-bold">
                Farm Parameters Ready for Analysis
              </h3>
              <p className="text-sm text-on-surface-variant max-w-md mx-auto">
                Click <strong className="text-white">&ldquo;Analyze My Farm&rdquo;</strong> above to generate real-time suitability scores and crop recommendations using Google Gemini AI.
              </p>
            </div>
          ) : recommendations.length === 0 ? (
            <div className="p-8 rounded-3xl bg-surface-container-low/50 border border-outline-variant/20 text-center">
              <p className="text-sm text-on-surface-variant">
                No verified crop recommendations returned. Consult your local extension office.
              </p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {recommendations.map((crop, idx) => (
                <div
                  key={idx}
                  className="bg-surface-container-low/80 backdrop-blur-xl border border-outline-variant/30 rounded-3xl p-6 shadow-xl space-y-5 hover:border-primary/50 transition-all flex flex-col justify-between"
                >
                  <div className="space-y-4">
                    <div className="flex items-start justify-between gap-2">
                      <div>
                        <span className="text-[10px] font-label-code-sm text-secondary uppercase tracking-widest font-bold">
                          Option #{idx + 1}
                        </span>
                        <h3 className="font-headline-sm text-xl text-white font-bold mt-0.5">
                          {crop.cropName}
                        </h3>
                      </div>
                      <div className="text-right">
                        <span className="inline-block px-2.5 py-1 rounded-full bg-primary/20 text-primary font-bold text-xs font-label-code-sm">
                          {crop.suitabilityScore}% Match
                        </span>
                      </div>
                    </div>

                    {/* Why Suitable */}
                    <div className="space-y-1.5">
                      <span className="text-[11px] font-label-code-sm uppercase text-on-surface-variant font-medium flex items-center gap-1">
                        <span className="material-symbols-outlined text-sm text-primary">check_circle</span>
                        Key Advantages
                      </span>
                      <ul className="space-y-1 text-xs text-on-surface leading-relaxed">
                        {crop.reasons.map((r, i) => (
                          <li key={i} className="flex items-start gap-1.5">
                            <span className="text-primary">•</span>
                            <span>{r}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    {/* Water & Risk */}
                    <div className="grid grid-cols-2 gap-2 pt-2 border-t border-outline-variant/20 text-xs">
                      <div>
                        <span className="text-[10px] font-label-code-sm text-on-surface-variant uppercase block">
                          Water Demand
                        </span>
                        <span className="font-semibold text-secondary capitalize">
                          {crop.waterRequirement}
                        </span>
                      </div>
                      <div>
                        <span className="text-[10px] font-label-code-sm text-on-surface-variant uppercase block">
                          Estimated Yield
                        </span>
                        <span className="font-semibold text-on-surface">
                          {crop.estimatedYield || 'Regional Average'}
                        </span>
                      </div>
                    </div>

                    {crop.majorRisks && crop.majorRisks.length > 0 && (
                      <div className="space-y-1">
                        <span className="text-[10px] font-label-code-sm text-error uppercase font-medium flex items-center gap-1">
                          <span className="material-symbols-outlined text-xs">warning</span>
                          Primary Risks
                        </span>
                        <p className="text-[11px] text-on-surface-variant">
                          {crop.majorRisks.join(', ')}
                        </p>
                      </div>
                    )}
                  </div>

                  <div className="pt-3 border-t border-outline-variant/20">
                    <Link
                      href="/copilot"
                      className="w-full py-2.5 rounded-xl bg-surface-container-high hover:bg-surface-container-highest text-primary text-xs font-label-code-sm uppercase font-bold text-center block transition-colors"
                    >
                      Plan Sowing with AI Copilot
                    </Link>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </StitchShell>
  )
}
